import type { EventKey } from './types';

export const DEFAULT_KEYS = {
  ctrl: event => event.ctrlKey || event.metaKey,
  shift: event => event.shiftKey,
  alt: event => event.altKey,
  a: event => event.key.toLowerCase() === 'a',
  b: event => event.key.toLowerCase() === 'b',
  c: event => event.key.toLowerCase() === 'c',
  d: event => event.key.toLowerCase() === 'd',
  e: event => event.key.toLowerCase() === 'e',
  f: event => event.key.toLowerCase() === 'f',
  g: event => event.key.toLowerCase() === 'g',
  h: event => event.key.toLowerCase() === 'h',
  i: event => event.key.toLowerCase() === 'i',
  j: event => event.key.toLowerCase() === 'j',
  k: event => event.key.toLowerCase() === 'k',
  l: event => event.key.toLowerCase() === 'l',
  m: event => event.key.toLowerCase() === 'm',
  n: event => event.key.toLowerCase() === 'n',
  o: event => event.key.toLowerCase() === 'o',
  p: event => event.key.toLowerCase() === 'p',
  q: event => event.key.toLowerCase() === 'q',
  r: event => event.key.toLowerCase() === 'r',
  s: event => event.key.toLowerCase() === 's',
  t: event => event.key.toLowerCase() === 't',
  u: event => event.key.toLowerCase() === 'u',
  v: event => event.key.toLowerCase() === 'v',
  w: event => event.key.toLowerCase() === 'w',
  x: event => event.key.toLowerCase() === 'x',
  y: event => event.key.toLowerCase() === 'y',
  z: event => event.key.toLowerCase() === 'z',
  plus: event => event.key.toLowerCase() === '+',
  minus: event => event.key.toLowerCase() === '-'
} as const satisfies EventKey;
